### ISSUE TITLE
Drill 1.0

### ISSUE THREAD

**Issue by razb** [mapr-emea/apache-drill-jdbc-plugin#1]
Any chance of updating this for Drill 1.0? 

BTW, thanks for the contribution! This was very much needed.

**Comment by magpierre** [comment]
Hello and thanks! I will probably not have time to do a 1.0.0 port as it looks right now. FYI: I've already migrated the code directly to 1.1.0  (based on the latest code avail on github) but it is not checked in yet since 1.1.0 isn't released.

**Comment by afrozl** [comment]
Hi,

Now that Drill 1.1 is released, will you be updating this plugin?

Thanks

**Comment by magpierre** [comment]
Branch 1.1.0 is developed on the latest main code meaning it should work with the newly released version. I will do some tests and merge i to main once I've tested.
